name: Kittygram CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      
      - name: Run flake8
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run tests
        run: python manage.py test

  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test -- --watchAll=false

  build-and-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend
        run: |
          cd backend
          docker build -t gevork23/kittygram_backend:latest .
          docker push gevork23/kittygram_backend:latest
      
      - name: Build and push frontend
        run: |
          cd frontend
          docker build -t gevork23/kittygram_frontend:latest .
          docker push gevork23/kittygram_frontend:latest
      
      - name: Build and push gateway
        run: |
          cd nginx
          docker build -t gevork23/kittygram_gateway:latest .
          docker push gevork23/kittygram_gateway:latest

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.production.yml,.env"
          target: "~/kittygram/"
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/kittygram
            
            echo "=== Остановка старых контейнеров ==="
            sudo docker compose -f docker-compose.production.yml down || true
            
            echo "=== Pulling latest images ==="
            sudo docker compose -f docker-compose.production.yml pull
            
            echo "=== Starting containers ==="
            sudo docker compose -f docker-compose.production.yml up -d
            
            echo "=== Waiting for services ==="
            sleep 30
            
            echo "=== Running migrations ==="
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate --noinput || echo "Migrations might have failed"
            
            echo "=== Collecting static ==="
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --noinput || echo "Collectstatic might have failed"
            
            echo "=== Checking services ==="
            sudo docker compose -f docker-compose.production.yml ps
            
            echo "=== Checking application ==="
            curl -f http://localhost:9000/ || echo "Application might be loading..."
            
            echo "=== Deployment completed! ==="

  notify:
    name: Send Telegram notification
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    
    steps:
      - name: Send Telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
        run: |
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            STATUS="✅ Успешный деплой Kittygram"
            EMOJI="🎉"
          else
            STATUS="❌ Ошибка при деплое Kittygram"
            EMOJI="😞"
          fi
          
          MESSAGE="${STATUS} ${EMOJI}
          Репозиторий: ${{ github.repository }}
          Ветка: ${{ github.ref_name }}
          Коммит: ${GITHUB_SHA::7}
          Сайт: https://oski.myftp.biz/"
          
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE"