name: Kittygram CI/CD

on:
  push:
    branches: [ main ]

jobs:
  tests_backend:
    name: Test backend
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
          POSTGRES_DB: kittygram
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install flake8==6.0.0 flake8-isort==7.0.0
          pip install -r ./backend/requirements.txt
      
      - name: Test with flake8 and django tests
        env:
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
          POSTGRES_DB: kittygram
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: test-secret-key
          DEBUG: True
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test

  tests_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend/
          npm ci

      - name: Test frontend
        run: |
          cd frontend/
          npm run test

  build_and_push_backend:
    runs-on: ubuntu-latest
    needs: tests_backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: gevork23/kittygram_backend:latest

  build_and_push_frontend:
    name: Build and push frontend
    runs-on: ubuntu-latest
    needs: tests_frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: gevork23/kittygram_frontend:latest

  build_and_push_gateway:
    name: Build and push gateway
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push gateway
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: gevork23/kittygram_gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build_and_push_backend
      - build_and_push_frontend
      - build_and_push_gateway
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Copy files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.production.yml,.env.example"
          target: "kittygram"
    
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Установка docker-compose если нет
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing docker-compose..."
              sudo apt update
              sudo apt install docker-compose -y
            fi

            cd kittygram

            # Проверяем наличие .env файла
            if [ ! -f ".env" ]; then
              echo "ERROR: .env file not found! Please create .env file on the server."
              echo "You can use .env.example as a template:"
              echo "cp .env.example .env"
              echo "Then edit .env with your settings."
              exit 1
            fi

            echo "Using existing .env file"
          
            echo "=== Pulling latest images ==="
            sudo docker pull gevork23/kittygram_backend:latest || true
            sudo docker pull gevork23/kittygram_frontend:latest || true
            sudo docker pull gevork23/kittygram_gateway:latest || true
          
            echo "=== Stopping old containers ==="
            sudo docker-compose -f docker-compose.production.yml down || true
          
            echo "=== Starting new containers ==="
            sudo docker-compose -f docker-compose.production.yml up -d
          
            echo "=== Waiting for services ==="
            sleep 30
          
            echo "=== Running migrations ==="
            sudo docker-compose -f docker-compose.production.yml exec -T backend python manage.py migrate --noinput
          
            echo "=== Collecting static ==="
            sudo docker-compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput
          
            echo "=== Restarting to apply changes ==="
            sudo docker-compose -f docker-compose.production.yml restart
          
            echo "=== Checking services ==="
            sudo docker-compose -f docker-compose.production.yml ps
          
            echo "=== Testing connectivity ==="
            curl -f http://localhost:9000/ && echo "✅ Kittygram deployed successfully"
          
            echo "=== Deployment completed! ==="

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Kittygram deployment
            Status: ${{ needs.deploy.result }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${GITHUB_SHA::7}
            Site: https://oski.myftp.biz/