name: Kittygram CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      
      - name: Run flake8
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run tests
        run: python manage.py test

  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test

  build-and-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: gevork23/kittygram_backend:latest
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: gevork23/kittygram_frontend:latest
      
      - name: Build and push gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: gevork23/kittygram_gateway:latest

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.production.yml,.env"
          target: "~/kittygram/"
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/kittygram
            echo "Pulling latest images..."
            sudo docker compose -f docker-compose.production.yml pull
            echo "Starting containers..."
            sudo docker compose -f docker-compose.production.yml up -d --build
            sleep 10
            echo "Running migrations..."
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate --noinput
            echo "Collecting static files..."
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --noinput
            echo "Copying frontend static files..."
            sudo docker compose -f docker-compose.production.yml exec frontend sh -c "cp -r /app/build/. /frontend_static/"
            echo "Copying backend static files..."
            sudo docker compose -f docker-compose.production.yml exec backend sh -c "cp -r /app/collected_static/. /staticfiles/"
            echo "Setting permissions..."
            sudo docker compose -f docker-compose.production.yml exec backend sh -c "chmod -R 755 /staticfiles"
            sudo docker compose -f docker-compose.production.yml exec backend sh -c "chmod -R 755 /media"
            echo "Deployment completed!"

  notify:
    name: Send Telegram notification
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    
    steps:
      - name: Send Telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
        run: |
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            STATUS="✅ Успешный деплой Kittygram"
            EMOJI="🎉"
          else
            STATUS="❌ Ошибка при деплое Kittygram"
            EMOJI="😞"
          fi
          
          MESSAGE="${STATUS} ${EMOJI}
          Репозиторий: ${{ github.repository }}
          Ветка: ${{ github.ref_name }}
          Коммит: ${GITHUB_SHA::7}"
          
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE" \
            -d parse_mode="HTML"